### PR TITLE
implementation of SA1139UseLiteralSuffixNotationInsteadOfCasting 

### PR DESCRIPTION
**Pull request by tmaczynski**
First working and tested implementation of #1562

### CODE REVIEW

**Comment by pdelvo** [comment]
I reviewed this PR and this looks mostly fine. I don't like the use of regular expressions. This would also have to be updated for C#7 with its binary literals and literal seperators. I played around with it a little bit and I came up with a solution that does not rely on them. I sent you a PR (tmaczynski/StyleCopAnalyzers#1) so you can have a look.

**Comment by tmaczynski** [comment]
Hi,
Thank you for review, I've merged you changes. I've also added one trivial change to this pull request (4434257).

I really like that you used SemanticModel API and deleted my extension methods (which are redundant).
If you prefer imperative loop to regex, I think that all other changes also make sense - especially that you code works better when C# 7 code is analysed.

**Comment by tmaczynski** [comment]
I've resolved conflicts between tmaczynski:sa1139 topic branch and master.

**Comment by tmaczynski** [comment]
Could you merge my changes or give me more feedback?

**Comment by pdelvo** [comment]
Loogs good to me :+1:

**Pull request merged**
