### PR TITLE
Implement alternative rules SX1309 and SX1309S

### LINKED ISSUE #837: SX1309: FieldNamesMustBeginWithUnderscore
This is the standard alternative rule to SA1309 (FieldNamesMustNotBeginWithUnderscore).

A violation of this rule occurs when a field name does not begin with an underscore. This rule only examines fields which are *all* of the following:

* `private`
* Instance (not `static`)
* Not `const`

### LINKED ISSUE #838: SX1309S: StaticFieldNamesMustBeginWithUnderscore
This rule expands on the coverage of SX1309 (FieldNamesMustBeginWithUnderscore) (#837) to cover static fields in addition to instance fields.

A violation of this rule occurs when a field name does not begin with an underscore. This rule only examines fields which are *all* of the following:

* `private`
* `static`
* Not `const`
* Not `readonly`

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #837
Fixes #838

### CODE REVIEW

**Comment by vweijsters** [comment]
I think it would be a good idea to create a test base class, as both test classes are large duplicates of each other.

**Comment by vweijsters** [comment]
Both analyzers are very similar as well and probably could benefit from a base class as well, most likely even combined with SA1309.

**Comment by vweijsters** [comment]
:+1: Besides the two minor remarks above, it looks very good.

**Comment by sharwell** [comment]
Sharing a test base class doesn't share nearly as much as was hoped, because the `[MemberData]` attribute only works with static members.

**Comment by vweijsters** [comment]
That will make things very difficult indeed and not worth the effort for just two classes.

**Pull request merged**
