### PR TITLE
Fixed issues with SX1101 analyzer

### LINKED ISSUE #1706: SX1101 incorrectly reported for local variable that hides field
SX1101 is reported for the use of `this.` in the following code. The code fix results in a compilation error.

```csharp
class ClassName
{
  int items;
  void Method()
  {
    var items = this.items;
  }
}
```

### LINKED ISSUE #1707: SX1101 incorrectly reported for parameter that hides field
SX1101 is reported for the use of `this.` in the following code. The code fix results in a compilation warning (assignment made to same variable) and (more importantly) a change in code behavior.

```csharp
class ClassName
{
  int items;
  void Method(int items)
  {
    this.items = items;
  }
}
```

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #1707 
Fixes #1706

### CODE REVIEW

**Comment by sharwell** [comment]
I'm seeing SX1101 reported for the following. Not sure if you want a separate issue for it.

```csharp
class ClassName
{
  string P => string.Empty;

  public void Method()
  {
    int value = this.P();
  }
}

static class ClassNameExtensions
{
  public static int P(this ClassName instance) => 3;
}
```

**Comment by sharwell** [comment]
:laughing: Also this

```csharp
class BaseClass
{
  protected int Options => 3;
}

class DerivedClass : BaseClass
{
  void Method<Options>()
  {
    int options = this.Options;
  }
}
```

**Comment by sharwell** [comment]
Also this:

```csharp
class ClassName
{
  int value;

  int Value
  {
    get { return value; }
    set { this.value = value; }
  }
}
```

**Comment by sharwell** [comment]
Also this:

```csharp
class ClassName
{
  int @object;

  ClassName(int @object)
  {
    this.@object = @object;
  }
}
```

**Comment by sharwell** [comment]
Also this (all three instances of `this` are required, but all three are removed):

```csharp
class ClassName
{
  object p;

  object Property
  {
    get
    {
      if (this.p != null) return this.p;
      object p = new object();
      return this.p = p;
    }
  }
}
```

**Comment by sharwell** [comment]
@vweijsters See #1719 for a possible alternative to this.

**Comment by vweijsters** [comment]
I'm happy with the alternative, closing this.

**Pull request closed without merging**
