### PR TITLE
Initial conversion of HTML to markdown

### PR DESCRIPTION
**Pull request by sharwell**
The conversion was performed using the following PowerShell script.

```powershell
Function TransformStyleCop($file)
{
  $xslt = New-Object System.Xml.Xsl.XslCompiledTransform
  $xslt.Load($pwd.Path + '\TranslateToMarkdown.xslt')
  $xslt.Transform($pwd.Path + '\' + $file, $pwd.Path + '\' + [System.IO.Path]::ChangeExtension($file, '.md'))
}

Get-ChildItem *.html | ? { TransformStyleCop($_.Name) }
```

Each of the Markdown files still needs to be verified for accuracy against the original documentation for the diagnostic. After the verification is complete, we can work to document any known differences between StyleCopAnalyzers and StyleCop "classic".

## Verification checklist

* Spacing rules
  * [x] SA1000
  * [x] SA1001
  * [x] SA1002
  * [x] SA1003
  * [x] SA1004
  * [x] SA1005
  * [x] SA1006
  * [x] SA1007
  * [x] SA1008
  * [x] SA1009
  * [x] SA1010
  * [x] SA1011
  * [x] SA1012
  * [x] SA1013
  * [x] SA1014
  * [x] SA1015
  * [x] SA1016
  * [x] SA1017
  * [x] SA1018
  * [x] SA1019
  * [x] SA1020
  * [x] SA1021
  * [x] SA1022
  * [x] SA1023
  * [x] SA1024
  * [x] SA1025
  * [x] SA1026
  * [x] SA1027
  * [x] SA1028
* Readability rules
  * [x] SA1100
  * [x] SA1101
  * [x] SA1102
  * [x] SA1103
  * [x] SA1104
  * [x] SA1105
  * [x] SA1106
  * [x] SA1107
  * [x] SA1108
  * [x] SA1109
  * [x] SA1110
  * [x] SA1111
  * [x] SA1112
  * [x] SA1113
  * [x] SA1114
  * [x] SA1115
  * [x] SA1116
  * [x] SA1117
  * [x] SA1118
  * [x] SA1120
  * [x] SA1121
  * [x] SA1122
  * [x] SA1123
  * [x] SA1124
  * [x] SA1125
  * [x] SA1126
* Ordering rules
  * [x] SA1200
  * [x] SA1201
  * [x] SA1202
  * [x] SA1203
  * [x] SA1204
  * [x] SA1205
  * [x] SA1206
  * [x] SA1207
  * [x] SA1208
  * [x] SA1209
  * [x] SA1210
  * [x] SA1211
  * [x] SA1212
  * [x] SA1213
  * [x] SA1214
  * [x] SA1215
  * [x] SA1216
  * [x] SA1217
* Naming rules
  * [x] SA1300
  * [x] SA1301
  * [x] SA1302
  * [x] SA1303
  * [x] SA1304
  * [x] SA1305
  * [x] SA1306
  * [x] SA1307
  * [x] SA1308
  * [x] SA1309
  * [x] SA1310
  * [x] SA1311
* Maintainability rules
  * [x] SA1119
  * [x] SA1400
  * [x] SA1401
  * [x] SA1402
  * [x] SA1403
  * [x] SA1404
  * [x] SA1405
  * [x] SA1406
  * [x] SA1407
  * [x] SA1408
  * [x] SA1409
  * [x] SA1410
  * [x] SA1411
  * [x] SA1412
* Layout rules
  * [x] SA1500
  * [x] SA1501
  * [x] SA1502
  * [x] SA1503
  * [x] SA1504
  * [x] SA1505
  * [x] SA1506
  * [x] SA1507
  * [x] SA1508
  * [x] SA1509
  * [x] SA1510
  * [x] SA1511
  * [x] SA1512
  * [x] SA1513
  * [x] SA1514
  * [x] SA1515
  * [x] SA1516
  * [x] SA1517
  * [x] SA1518
  * [x] SA1519
  * [x] SA1520
* Documentation rules
  * [x] SA1600
  * [x] SA1601
  * [x] SA1602
  * [x] SA1603
  * [x] SA1604
  * [x] SA1605
  * [x] SA1606
  * [x] SA1607
  * [x] SA1608
  * [x] SA1609
  * [x] SA1610
  * [x] SA1611
  * [x] SA1612
  * [x] SA1613
  * [x] SA1614
  * [x] SA1615
  * [x] SA1616
  * [x] SA1617
  * [x] SA1618
  * [x] SA1619
  * [x] SA1620
  * [x] SA1621
  * [x] SA1622
  * [x] SA1623
  * [x] SA1624
  * [x] SA1625
  * [x] SA1626
  * [x] SA1627
  * [x] SA1628
  * [x] SA1629
  * [x] SA1630
  * [x] SA1631
  * [x] SA1632
  * [x] SA1633
  * [x] SA1634
  * [x] SA1635
  * [x] SA1636
  * [x] SA1637
  * [x] SA1638
  * [x] SA1639
  * [x] SA1640
  * [x] SA1641
  * [x] SA1642
  * [x] SA1643
  * [x] SA1644
  * [x] SA1645
  * [x] SA1646
  * [x] SA1647
  * [x] SA1648
  * [x] SA1649
  * [x] SA1650
  * [x] SA1651
  * [x] SA1652
* Alternative rules
  * [x] SX1309
  * [x] SX1309S

### CODE REVIEW

**Comment by sharwell** [comment]
:memo: This pull request is a straight conversion of the original HTML content to Markdown. I'm planning to leave all editing, including updates for disabled rules and intentional deviations from StyleCop "classic", for later updates.

@pdelvo @vweijsters Any reason not to merge this?

**Comment by vweijsters** [comment]
:+1: Looks good to me

**Comment by pdelvo** [comment]
It might be a good idea to write a unit test that verifies that all help links pinkt to an url on github to make sure we dont forget any diagnostic.

**Comment by otac0n** [comment]
@pdelvo :+1:

**Comment by sharwell** [comment]
@pdelvo @otac0n Added tests.

**Comment by otac0n** [comment]
:+1:

**Pull request merged**
