### PR TITLE
Create and use a JSON object model for stylecop.json

### PR DESCRIPTION
**Pull request by sharwell**
* Add `copyrightText` to the JSON schema
* Add `variables` to the JSON schema

This addresses some of the concerns in #1243. I believe the remaining concerns can be addressed by selectively disabling the XML structure of the file headers, and using *just* the `copyrightText` value.

### CODE REVIEW

**Comment by vweijsters** [comment]
:+1: Looks good to me

**Comment by vweijsters** [comment]
:+1: Latest changes look good as well

**Comment by DavidDeSloovere** [comment]
Might "organizationName" be a better alternative to "companyName"? I'm thinking OSS projects...

**Comment by sharwell** [comment]
@DavidDeSloovere If this was a new feature, that would probably be desirable. However, this is a carry-over from StyleCop "classic" and the settings name was chosen to match the name of the XML attribute that appears in the source code for the standard StyleCop header.

If you really want to get rid of `companyName` in the header, you can use the advanced customization that is coming as part of #1271.

**Pull request merged**
