### PR TITLE
Fixed SA1610 to ignore <inheritdoc/> for properties that do not overr…

### LINKED ISSUE #1945: SA1610 inheritdoc analysis does not consider overrides
The following code should report SA1610, but no warning is reported.

```csharp
/// <value>
/// </value>
/// <inheritdoc/>
public string Property => "P";
```

### PR DESCRIPTION
**Pull request by vweijsters**
…ide / implement an interface.

Fixes #1945

### CODE REVIEW

**Comment by sharwell** [comment]
It looks like I failed to explain the issue correctly. In the example code in #1945, the problem lies in the fact that the `<value>` element will prefer to use one included in the comment itself (if any), and only fall back to using the inherited value if none is present. Our analysis currently assumes that the inline value is ignored if `<inheritdoc/>` is specified.

**Comment by vweijsters** [comment]
:question: That would effectively mean that we can remove any check on `<inheritdoc/>` if the `<value>` element is present, right?

**Comment by sharwell** [comment]
@vweijsters At least for SA1610, yes that is correct.

**Comment by vweijsters** [comment]
@sharwell I've updated the code to reflect the discussion above. Can you have a look and see if this is what you intended?

**Pull request closed without merging**
