### PR TITLE
Support C# 7 via light-up

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by sharwell** [comment]
@vweijsters @pdelvo This could benefit from additional tests, but I believe I have it in a state where we can start working in parallel using it to fix some of the outstanding C# 7 problems.

**Comment by roterdam** [comment]
Is there a released version of this change?

**Comment by sharwell** [comment]
@roterdam This PR allows us to support C# 7, but doesn't actually update any of the rules to use it. We're still working on updating the rules themselves but I'm hoping to release the first beta that includes this work soon.

**Comment by roterdam** [comment]
thank you, eagerly waiting for this as I don't want to remove StyleCop just to use C# 7 features.

**Pull request merged**
