### PR TITLE
Added extension point to DiagnosticVerifier

### PR DESCRIPTION
**Pull request by vweijsters**
Added the CreateSolution extension point to the DiagnosticsVerifier, in order to get control over solution properties.

### CODE REVIEW

**Comment by sharwell** [comment]
@vweijsters I would prefer to wait on this for now. Do you mind if I close it as `wontfix` until such time as we hit a case that is substantially impacted by it?

**Comment by vweijsters** [comment]
SA1502 (#547) uses this to test the indentation code in the code fixer. 
If we are okay with only testing for 4 spaces indentation in the unit tests, then I'm fine with closing this.

**Comment by sharwell** [comment]
Thanks, I'll keep this open at least until I review that. :smile:

**Comment by vweijsters** [comment]
Merged in upstream/master

**Comment by pdelvo** [comment]
I could use this to add a test for #929.

**Pull request merged**
