### PR TITLE
Update to Visual Studio 2015 CTP 5

### PR DESCRIPTION
**Pull request by sharwell**
This pull request updates the project to Visual Studio 2015 CTP 5.

It is currently blocked on dotnet/roslyn#23, which is causing a total of 10 tests to fail.

### CODE REVIEW

**Comment by sharwell** [comment]
The issue with formatting has been fixed by the introduction of a `WithoutElasticTrivia()` extension method for `SyntaxNode`, `SyntaxToken`, and `SyntaxTrivia`.

**Comment by pdelvo** [comment]
looks good

**Comment by sharwell** [comment]
@pdelvo Thanks for reviewing this so quickly. :smile: Can you look at the changes made in the last commit as well?

**Comment by pdelvo** [comment]
Looks good too. Why did you put the SpacingExtensions.cs under StyleCop.Analyzers/SpacingRules/? it could be usefull for other diagnostics as well so I think StyleCop.Analyzers/Helpers/ would be better

**Comment by sharwell** [comment]
It was added back when the only code fixes were for spacing rules. I left it there for now; I'm torn on the name **/Helpers/** so I think they may both get refactored in the future (and probably together).

**Pull request merged**
