### PR TITLE
Reference stylecop.json schema file in docs

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by sharwell** [comment]
:bulb: I would prefer to see this as a separate subsection of the Getting Started section, which explains the `"$schema"` property and its advantage (mostly IntelliSense in Visual Studio).

**Comment by AArnott** [comment]
I also wondered where the code fixer was so we can get the original file generated to include this as well. Can you point me to it?

**Comment by sharwell** [comment]
I thought it already did include it? 

I'm AFK for a bit but will check on it soon.

**Comment by sharwell** [comment]
@AArnott Yes, [it's already included](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/SettingsFileCodeFixProvider.cs#L25) in the default template.

**Comment by AArnott** [comment]
Oh!

**Comment by sharwell** [comment]
Superseded by #1414.

**Comment by AArnott** [comment]
Great. :) Less work for me.

**Pull request closed without merging**
