### PR TITLE
Issue #3402: Removed creation of CultureInfo with arbitrary names

### PR DESCRIPTION
**Pull request by bjornhellander**
Attempted fix for #3402. A bit of a hack :-), but should hopefully work.

Note: I haven't been able to verify this fix on my machine, due to not understanding how, but the problematic calls to the CultureInfo constructor with a culture name are gone. I can try again if someone can explain what to do.

### CODE REVIEW

**Comment by bjornhellander** [comment]
A test for SA1134 failed on the release build. I have seen this sometimes before this pr and have now run the tests locally a couple of times again without any problems. Pushing again to trigger a new build.

**Comment by bjornhellander** [comment]
Oookey. No code changes relative to the first push and now lots of tests fail with one of the following exceptions:
- System.Runtime.InteropServices.COMException : Signature specified is zero-sized
- System.BadImageFormatException : Bad binary signature

Stilll don't think this is related to my change, so pushing again to trigger a new build.

**Review by sharwell — CHANGES_REQUESTED** [review]
Based on an internal discussion, this change does not appear to adhere to the design/intent of `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`. The documented approach to handling this situation is setting one of the following environment variables:

* Set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to `false`
* Set `DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY` to `false`

If I get a new suggestion from the team that implemented this option, we may reconsider the approach used by this tool.

Separately, we would accept a change to make the _default_ culture work in this configuration (i.e. cases where `DocumentationCulture` has not been set). The solution in this case is to use the invariant culture directly instead of trying to create a new instance of a different culture.

**Comment by sharwell** [comment]
I submitted #3426 separately to make the default value "en-US" work with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`.

**Comment by sharwell** [comment]
Superseded by #3426

**Pull request closed without merging**
