### PR TITLE
Implemented SA1409 RemoveUnnecessaryCode

### LINKED ISSUE #98: SA1409: RemoveUnnecessaryCode
http://www.stylecop.com/docs/SA1409.html

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #98. I might add a code fix later

### CODE REVIEW

**Comment by macpak** [comment]
Pretty damn good job :)
I am only wondering if we should keep a parameterless constructor with empty body. 
In my opinion it makes sense in 2 cases:
- if you have another constructor(s) which takes some parameters, and you keep the parameterless constructor in order to avoid breaking code that depends on it . 
- if the constructor calls a base constructor.
Stylecop doesn't report this issue as well.
What do you think Dennis ?

**Comment by pdelvo** [comment]
Thanks ;)
Im only reporting static constructors which get called only once when a class gets used for the first time. You can't explicitly call it and it cant have any parameters or have a base call

**Comment by macpak** [comment]
Yeah, my whole story was about nonstatic constructors :)

**Comment by sharwell** [comment]
Also if it's not public or (for abstract classes) protected. 

Also if it has XML documentation comments. 

The base call doesn't count as necessary if it doesn't pass any arguments.

**Comment by sharwell** [comment]
Marking **wontfix** based on #1058.

**Pull request closed without merging**
