### PR TITLE
Updated documentation of AnalyzerExtensions

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by Noryoko** [comment]
:+1:

**Comment by otac0n** [comment]
Just FYI: you should not be doing this pattern:

    <see cref="Diagnostic"/>s

You should prefer this:

    <see cref="Diagnostic">Diagnostics</see>

**Comment by sharwell** [comment]
@otac0n My general preference is to use sentence structures that avoid plural forms of type names. The problem with the form you suggested is preferred is it immediately becomes incorrect if you rename the type. In the form I used, the pluralization might not be correct but the refactoring would at least update the text to match the new name.

**Comment by otac0n** [comment]
"Refactorability over readability" is untenable in documentation.

**Comment by sharwell** [comment]
> "Refactorability over readability" is untenable in documentation.

Either without the other is sub-optimal. I added you to our Gitter room - I'll send you some links to material I've been working on. :smile:

**Comment by otac0n** [comment]
Looks good.

**Pull request merged**
