### PR TITLE
SA1010 now properly supports index initializers

### LINKED ISSUE #1617: SA 1010 clashes with SA 1012 in Index initializers case.
The following code produces SA 1010, 'Fix spacing' code fix leads to SA 1012:

```CSharp 
new Dictionary<ulong, string>(items) { [100] = "100" } 
```

### PR DESCRIPTION
**Pull request by vweijsters**
Fixes #1617

### CODE REVIEW

**Comment by sharwell** [comment]
In the following code snippet, would the current implementation fail to report a diagnostic for the space in `indexes [`?

```csharp
int[] indexes = { 0 };
var dictionary = new Dictionary<int, int> { [indexes [0]] = 0 };
```

**Comment by vweijsters** [comment]
It would. I'll address that.

**Comment by vweijsters** [comment]
Updated

**Comment by sharwell** [comment]
:+1: This is merged and waiting for the AppVeyor build to complete.

**Pull request merged**
