### PR TITLE
Implemented SA1628.

### LINKED ISSUE #148: SA1628: DocumentationTextMustBeginWithACapitalLetter

### LINKED ISSUE #149: SA1629: DocumentationTextMustEndWithAPeriod
~~http://www.stylecop.com/docs/SA1629.html~~
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md

### PR DESCRIPTION
**Pull request by dlemstra**
This pull requests implements SA1628 and adds a CodeFixProvider for SA1628 and this will resolve #148. This is my first attempt to write an Analyzer and a CodeFixProvider so please let me know if I can make some improvements. I am not sure if my solution for skipping the CodeFixProvider when something is found inside an "include" is correct but I could not find a better solution. Once this merge request has been reviewed and merged I will start to work on implementing SA1629.

Fixes #148

### CODE REVIEW

**Comment by sharwell** [comment]
@dlemstra In case you're curious, the following link shows the code coverage for just the lines of code you wrote:
https://codecov.io/gh/DotNetAnalyzers/StyleCopAnalyzers/pull/2242/compare

I notice that `CheckElement` and `CheckIfFirstLetterUppercase` are the two methods missing coverage in areas. If you don't get to it earlier, I'll take a closer look when reviewing this later to propose some additional test cases that cover the edge cases for these methods. 😄

**Comment by dlemstra** [comment]
@sharwell I can add some extra test cases tonight.

**Comment by sharwell** [comment]
@dlemstra SA1628 is marked as "won't fix by design/intent", so it's unlikely we would merge an implementation of it.

**Comment by dlemstra** [comment]
I personally would like to have this rule and SA1629 enabled  in my own projects. This should not be a rule that will be enabled by default though. I think there is no harm in having this in the library but keep it disabled by default. Would you or one of the other members consider re-opening/allowing SA1628?

**Pull request closed without merging**
