### PR TITLE
Disable SA1609 (PropertyDocumentationMustHaveValue) by default

### LINKED ISSUE #1262: SA1609 - The most annoying new feature.
SA1609 was not turned on by default in the old StyleCop.  It is, without question, the most annoying new feature of the new StyleCop in that the value added is negligible vs. the amount of work needed for compliance.  All of my properties have a standard 'Gets or sets' documentation.  The 'Value' description is redundant.  Is there some justification for this rule being on be default or was it just turned on by mistake?

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #1262

### CODE REVIEW

**Comment by pdelvo** [comment]
Do we want to enable the diagnostic for this project?

Otherwise: :+1:

**Comment by sharwell** [comment]
> Do we want to enable the diagnostic for this project?

Yes, we'll need to update the ruleset when the project is upgraded to Beta 9.

**Comment by pdelvo** [comment]
Couldn't you just include the ruleset change in this PR? Just set it manually to warning and it should just work when we upgrade.

**Comment by sharwell** [comment]
@pdelvo Updated

**Comment by pdelvo** [comment]
:+1: Looks good to me

**Pull request merged**
