### PR TITLE
Add custom kind order for SA1201 addressing 2541, 1610

### PR DESCRIPTION
**Pull request by mdepalma**
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1610
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2541

both asking for this customization

### CODE REVIEW

**Comment by mdepalma** [comment]
@sharwell do you have a few minutes to take a look at this? Since I haven't contributed to this project before I'm curious what else you'd be looking for before I'd be able to complete this.

Thanks!

**Comment by mdepalma** [comment]
Hi @sharwell - can you take a look at this?

**Comment by sharwell** [comment]
Resolving as **wontfix** per https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2541#issuecomment-533150009.

**Comment by sharwell** [comment]
Hi @mdepalma,

Considering we were never able to make the experience for this rule great even for a fixed order, I don't believe we'll be able to produce a great experience for an even more complicated configurable rule in the foreseeable future. If a customized rule is needed for your work, please do consider creating a custom analyzer just to handle this case for your project. SA1201 from this project can be disabled when you enable the custom rule.

Thanks!

**Pull request closed without merging**
