### PR TITLE
Fix expression body property documentation checks

### PR DESCRIPTION
**Pull request by lukas-ais**
I found, that documentation on expression body properties will not be checked correctly, if documentation starts with "Gets or sets". Expression body properties are read-only properties, so "or sets" is simply wrong.

The problem was introduced with pull request #1825, I guess just a misunderstanding.

Hope this fix is welcome and fulfill the coding guide. I currently see the following TODOs

1. Is it possible to have getter AND setter inaccessible, somehow? I wrote a TODO statement to raise e.g. an NotImplementedException. Needed this branch to ensure initialization of getterVisible and setterVisible.
2. I added DisplayName to the test methods. For me, this is helpful to identify individual tests in the Test Explorer of VS2015. I do not know, if there are side effects.

### CODE REVIEW

**Comment by lukas-ais** [comment]
Hi @vweijsters,

how to create a code review to get progress on this issue?
Other pull requests will be taken without code review.
This and question from #2094 would be quite interesting...

Thanks,
Lukas

**Comment by vweijsters** [comment]
@lukas-ais All pull requests will go through the code review process. Occasionally @sharwell will do the code review and if no issues are found he merges the pull request straight away, this might give the impression that no review has been done.

There is no fixed time scale for when issues will be reviewed and / or merged. It depends on the amount of time available for the contributors to work on it, as this project is run by volunteers.

**Comment by pdelvo** [comment]
Sorry that this took so long. The fix looks fine to me :+1:

**Comment by lukas-ais** [comment]
Hi @sharwell, I'm a bit confused on your merge.
Maybe I'm not fully familiar with github procedure, but I feel, you did not fully merge my changes.
Can you help me to understand?

Thank!

**Comment by sharwell** [comment]
@lukas-ais The indentation of a `switch` statement in **PropertySummaryDocumentationAnalyzer.cs** was off by one (indented too far), so I just went ahead and fixed that at the same time I merged the pull request. It was a whitespace-only change. It looks like I forgot to use the correct commit message on b638f6204645afbb9bb1c1536d86c4dc94c08514, where the first line should have been the following:

```
Merge pull request #2091 from lukas-ais/ExpressionBodyPropertyDocumentation
```

Aside from a trivial change in indentation, your pull request should be fully merged into the **master** branch now.

**Comment by lukas-ais** [comment]
So, I wonder why you did not merge my changes, made already months ago?
It is somehow frustrating, when I invest a lot of time to fix the problem, provide test code, then better test code to improve the code coverage, and at the end you (more or less) ignore my changes and doing the same effort again.
As already mentioned in #2094, the current process to handle contributions is unclear to me. I guess this will reduce the community feedback.

Later I will double-check if your changes matches my ones.

**Comment by sharwell** [comment]
@lukas-ais Your changes were merged. I did not duplicate the effort.

I am sorry it took so long to get this merged. :worried: I went through a major move earlier this year and it took away a bunch of my time.

**Pull request merged**
