### PR TITLE
Remove weird character from start of file

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by sharwell** [comment]
@adamralph The character is a UTF-8 byte order mark. The GitHub change which caused rendering to break has now been corrected (I worked with GitHub support over the weekend to point out the problem and recommend a solution, which has now been deployed).

**Comment by adamralph** [comment]
OK @sharwell np. I know about BOM's but I guess it was something else, since I've never seen them rendered in GitHub before.

**Comment by adamralph** [comment]
BTW - the editor is still rendering them, and allowing them to be deleted:

image

**Comment by sharwell** [comment]
@adamralph Thanks, I sent GitHub an update to the issue with a link to your comment and screenshot.

**Pull request closed without merging**
