### PR TITLE
Implement SA1410, SA1411 tests and code fixes

### LINKED ISSUE #309: Code fix unit tests: RemoveDelegateParenthesisWhenPossible
Implement unit tests for #308.

### PR DESCRIPTION
**Pull request by pdelvo**
I hope this are enough tests. These diagnostics are so basic that there isn't really much to test.
Fixes #309, #312, #311, #310, #308, #307.

#313 has to be merged first.

### CODE REVIEW

**Comment by sharwell** [comment]
Which one needs to be merged first?

**Comment by pdelvo** [comment]
I meant #313. The tests currently fail because the diagnostic itself is missing. So merging this does not make much sense before merging the diagnostic

**Comment by sharwell** [comment]
Can you set these to enabled-by-default as well?

**Comment by pdelvo** [comment]
I enabled the diagnostics by default. I will have a look at @macpak's PRs when I have time

**Comment by sharwell** [comment]
I think you accidentally enabled SA1409 instead of SA1411.

**Comment by sharwell** [comment]
:exclamation: Can you go ahead and add `WellKnownDiagnosticTags.Unnecessary` to SA1410 and SA1411 at the same time you address the issue with SA1409 I mentioned before?

**Comment by pdelvo** [comment]
Done

**Pull request merged**
