### PR TITLE
Package the same version of Newtonsoft.Json that we build against

### LINKED ISSUE #2290: TypeLoadException with .NET Core RC4 and malformed stylecop.json
I added StyleCop.Analyzers to my project and managed to manually add a ruleset file to the csproj.

# Creating the project
```
md test
cd test
dotnet new console
```

# The ruleset file
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="WebDAV-Server Ruleset" Description=" Rules for the WebDAV-Server project" ToolsVersion="15.0">
  <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
    <Rule Id="SA0001" Action="None" />
    <Rule Id="SA1101" Action="None" />
    <Rule Id="SA1300" Action="None" />
    <Rule Id="SA1309" Action="None" />
    <Rule Id="SA1400" Action="None" />
    <Rule Id="SA1503" Action="None" />
    <Rule Id="SA1600" Action="None" />
    <Rule Id="SA1633" Action="None" />
  </Rules>
</RuleSet>
```

# The project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <CodeAnalysisRuleSet>test.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

# The stylecop.json file

This file is malformed, because comments aren't allowed in the project.json file.

```json
{
  // ACTION REQUIRED: This file was automatically added to your project, but it
  // will not take effect until additional steps are taken to enable it. See the
  // following page for additional information:
  //
  // https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md

  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "documentationRules": {
      "documentInternalElements": false
    },
    "orderingRules": {
      "usingDirectivesPlacement": "outsideNamespace"
    }
  }
}
```

# Commands
```
dotnet restore
dotnet build
```

# Output
```
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(1,1): warning SA1200: Using directive must appear within a namespace declaration [C:\temp\test\test.csproj]
CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.SpecialRules.SA0002InvalidSettingsFile' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'System.Runtime.Serialization.Formatters.FormatterAssemblyStyle' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'. [C:\temp\test\test.csproj]
  test -> C:\temp\test\bin\Debug\netcoreapp1.0\test.dll

Build succeeded.

Program.cs(1,1): warning SA1200: Using directive must appear within a namespace declaration [C:\temp\test\test.csproj]
CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.SpecialRules.SA0002InvalidSettingsFile' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'System.Runtime.Serialization.Formatters.FormatterAssemblyStyle' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'. [C:\temp\test\test.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.02
```

# Expected output

Either a good error message that the project.json is invalid or accepting the json file and not throwing the `TypeLoadException`

# Additional information

The error doesn't appear when run from inside VS 2017.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #2290

### CODE REVIEW

**Comment by mikes-gh** [comment]
Please could you release a new nugget package to unblock netcore sdk 1.0.0 builds
Many thanks for your work

**Comment by sharwell** [comment]
I'll try to get 1.0.1 released today or this weekend.

**Comment by sharwell** [comment]
@mikes-gh The new update is available now!

**Comment by mikes-gh** [comment]
OK I'm getting build failures with 1.0.1

/usr/local/share/dotnet/sdk/1.0.1/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/local/share/dotnet/sdk/1.0.1/Roslyn/RunCsc.sh" exited with code 134. [/Users/MikeS/Repos/reports/src/Reports/Reports.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/1.0.1/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/local/share/dotnet/sdk/1.0.1/Roslyn/RunCsc.sh" exited with code 134. [/Users/MikeS/Repos/reports/src/Reports/Reports.csproj]
    0 Warning(s)
    1 Error(s)

If I switch back to 1.0.0 I get all the warnings as before but it does build.

**Comment by mikes-gh** [comment]
@sharwell I see 1.0.1 was pulled so I guess you know this didnt work.
Let me know if you need to test I cloned the the repo and can build using the build script  but not sure what build switch syntax to use to generate private nuget to test?

**Comment by codito** [comment]
@sharwell is there a `1.1.0-beta002` release planned with this fix?

**Pull request merged**
