### PR TITLE
Implement diagnostic SA1100 DoNotPrefixCallsWithBaseUnlessLocalImplementationExists

### LINKED ISSUE #34: SA1100: DoNotPrefixCallsWithBaseUnlessLocalImplementationExists
http://www.stylecop.com/docs/SA1100.html

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #34 

This implementation supersedes #333. I used the tests implemented by that pull request, but replaced the implementation with one based on "experimental compilations" to determine whether or not the `base.` expression is necessary on a case-by-case basis.

There is quite a bit of room available for optimizing this implementation (essentially by various forms of pruning), but this should allow us to start with a correct initial implementation.

### CODE REVIEW

**Comment by macpak** [comment]
This pull request blocks #334.

**Comment by pdelvo** [comment]
As I already said in #333: This PR looks good and I don't think we can do it better without putting much work into it

**Comment by macpak** [comment]
Ok.
When it's merged I will add the codefix.

**Comment by sharwell** [comment]
Thanks y'all. :+1: This was certainly a challenging one!

**Comment by macpak** [comment]
[I am talking to Microsoft](https://github.com/dotnet/roslyn/issues/200) if the problem we have here can be solved in a different way.

**Pull request merged**
