### PR TITLE
Improve performace of SystemDiagnosticsDebugDiagnosticBase by comparing strings

### LINKED ISSUE #733: SystemDiagnosticsDebugDiagnosticBase should check the method name before calling GetSymbolInfo
`GetSymbolInfo` is a (relatively) expensive call that appeared while investigating #732. We should check the text name of the method being invoked before calling `GetSymbolInfo` to filter out the vast majority of calls.

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #733.

### CODE REVIEW

**Comment by sharwell** [comment]
:exclamation: Can you add some unit tests that use `System.Debug` instead of just `Debug` to reference the class (since it's a slightly different tree)?

**Comment by pdelvo** [comment]
This change will actually break Debug diagnostic in an edge case.
```csharp
using Foo = System.Diagnostics.Debug;

class Foo
{
    void Bar()
    {
        Foo.Assert(false);
    }
}
```

**Comment by sharwell** [comment]
You sure about that? We are looking for `Assert`, not `Debug`.

**Comment by sharwell** [comment]
:exclamation: Also add a check with `using static`, where the call appears as:

```csharp
using static System.Diagnostics.Debug;

...

void Bar()
{
    Assert(false);
}
```

**Comment by pdelvo** [comment]
I implemented some unit tests and I fixed a bug i found while doing that

**Pull request merged**
