### PR TITLE
Implement custom fix all providers

### PR DESCRIPTION
**Pull request by sharwell**
Implement document-based fix all providers for:

* SA1506
* SA1509
* SA1510
* SA1511
* SA1513
* SA1514

Based on information found in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1293538.

### CODE REVIEW

**Comment by sharwell** [comment]
@RussKie this should fix the specific problems you saw.

**Comment by RussKie** [comment]
Thank you for the quick turnaround!
How can I test these?

**Comment by sharwell** [comment]
@RussKie Locally you could use this feed:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/4d9b3e3bb785a55f73b3029a843f0c0b73cc9ea7/NuGet.config#L9-L10

Version 1.2.0-beta.343 should have the fix for validation.

**Comment by sharwell** [comment]
@RussKie these are now part of the latest preview release!

**Comment by RussKie** [comment]
Awesome! Thank you

**Pull request merged**
