### PR TITLE
Document SA1107 behavior anomaly

### LINKED ISSUE #2862: SA1107 Round Tripping Fix Does Not Correct Violation
Utilizing the provided StyleCopTester.exe (this tool is very strong/awesome by the way thank you) and after putting it in CI under our code base a single file kept popping out; the resulting format resulted in no changes which may indicate an issue with SA1107's Fix.

I stripped down our utility program to the bare minimum and ran the trouble file through Delta Debugging (https://www.st.cs.uni-saarland.de/dd/) using this utility which produced this nonsensical minimal test case, any removal of any character in this file will cause it to pass.

```csharp
d({{};
```

Using the minimal test case I worked it backwards to produce a more readable scenario:

```csharp
namespace SA1107Bug
{
    class Program
    {
        //Minimal TestCase d({{};
        static void Main(string[] args)
        {
            {
                System.Console.WriteLine("Test");
            };
        }
    }
}
```

Line 10 triggers SA1107 using StyleCop.Analyzers 1.0.2 from NuGet.org but as you can see attempting to preview the fix results in no fixes available:

image

It looks like some work was done to fix some corner cases under #1543 but it is unclear if this is related.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #2862

### CODE REVIEW

**Comment by vweijsters** [comment]
❓ Is the linked issue number correct? The code in the test is very different from the reported issue.

**Comment by sharwell** [comment]
@vweijsters Yes, the reproducer for the issue is an empty statement following a block. The contents of the block were unnecessary to reproduce the issue. The test verifies three things:

1. A diagnostic is reported (on the `;`)
2. A code fix is offered
3. The code fix does not actually make any changes to the code

**Comment by vweijsters** [comment]
That part is clear to me. What I don't understand is the `[|;|]` construction in the test code. Would a single semicolon be enough?

**Comment by sharwell** [comment]
Ah! The `[|text|]` is markup syntax. It works when the diagnostic analyzer only has one supported `DiagnosticDescriptor` and means:

1. A diagnostic is reported with _exactly_ that span (start and end verified)
2. The diagnostic ID matches the descriptor
3. The diagnostic severity matches the default severity of the descriptor

**Comment by vweijsters** [comment]
Now its clear 😄

**Pull request merged**
