### PR TITLE
Update element documentation diagnostics to handle included documentation

### PR DESCRIPTION
**Pull request by nbarbettini**
Currently working through these issues:

- [x] SA1608 (#1900)
- [x] SA1611 (#1904)
- [x] SA1612 (#1905)
- [x] SA1613 (#1906)
- [x] SA1614 (#1907)
- [x] SA1616 (#1908)
- [x] SA1625 (#1915)
- [x] Cleanup

### CODE REVIEW

**Comment by nbarbettini** [comment]
No longer WIP. I finally got around to cleaning up and rebasing this. :smile: 

Ready for code review.

**Comment by vweijsters** [comment]
:+1: looks good to me

**Comment by pdelvo** [comment]
What is the status on this PR? It is 5 months old, was code reviewed but not merged. @sharwell If this is fine I can resolve them and merge this PR

**Comment by sharwell** [comment]
Merged :+1:

**Pull request merged**
