### PR TITLE
Fix TriviaHelper handling of SingleLineDocumentTrivia 

### PR DESCRIPTION
**Pull request by hvanbakel**
Fix for #1327

### CODE REVIEW

**Comment by sharwell** [comment]
Blocked on #1252.

**Comment by sharwell** [comment]
:question: I don't fully understand why this change is needed. Can you add a test which would fail prior to this change, but after this change passes?

**Comment by hvanbakel** [comment]
Before I couldn't use the function on trivia helper now that that's updated
I can, so I dropped the local implementation in favor of the shared one.

**Comment by vweijsters** [comment]
Just did a review and I have some issues with this:
* Both `WithoutBlankLines` and `WithoutLeadingBlankLines` have the same documentation comments, so its completely unclear what they do.
* The new `WithoutBlankLines` is aimed to replace the old `WithoutLeadingBlankLines`, but it is not functionaly equivalent. The old `WithoutLeadingBlankLines` would only strip leading blank lines in front of the token, and not (as `WithoutBlankLines`) strip all empty lines from the trivia.
* The issue that you try to resolve for the `SA1212SA1213CodeFixProvider` could have been resolved by using a call to `WithoutLeadingWhitespace()` as well. (`secondAccessor.GetFirstToken().LeadingTrivia.WithoutLeadingWhitespace()`)

In my opinion this does not solve #1327. Renaming the original `WithoutLeadingBlankLines` to `WithoutLeadingBlankLinesBeforeToken` and updating the documentation would be the preferred way.

**Comment by pdelvo** [comment]
Do we still want to move this PR forward?

**Comment by vweijsters** [comment]
Based on my earlier comments I would say no.

**Comment by hvanbakel** [comment]
I would drop it too :).

**Pull request closed without merging**
